AllCops:
  Includes:
    - metadata.rb
    - Gemfile
    - attributes/**
    - recipes/**
    - libraries/**
    - providers/**
    - resources/**
  Excludes:
    - test/**
    - vendor/**


LineLength:
  Max: 110

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile
